version: '2'    

services:  
  geth-api-server:
    image: ethereum/client-go:latest
    restart: always
    volumes:
      - ./eth/data/:/root/.ethereum        
    expose:
      - "8545"
      - "8586"
      - "30303/udp"
      - "30304/udp"
    ports:
      - "8545:8545"
      - "8586:8586"
      - "30303:30303"
      - "30303:30303/udp"
      - "30304:30304"
      - "30304:30304/udp"
    command: "--rpc --rpcapi db,eth,net,web3,personal --rpcaddr 0.0.0.0"
